name: Java CI with Gradle

on:
  push:
    branches: [ "main", "1.21-1", "1.21.2-5" ]
  pull_request:
    branches: [ "main", "1.21-1", "1.21.2-5" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.14'
    
    # - name: Build with Gradle 8.14
    #   run: gradle build

    - name: Build with Gradle 8.14
      run: chmod +x build_all.sh && ./build_all.sh
      shell: bash

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path: "build/libs/*.jar"
